using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Midterm350.Models;
using System.Reflection.Emit;

namespace Midterm350.Data
{
    public class ApplicationDbContext : IdentityDbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }
        public DbSet<Veterinarian> Vets { get; set; }
        public DbSet<Patient> Patients { get; set; }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            //Images of vets and patients are from gettyimages.
            builder.Entity<Veterinarian>().HasData(
                new Veterinarian { Id = 1, Name = "Jackie", YearsExperience = 10, Bio = "I am an experienced vet who has many years of experience working with pets! I personally have a cat named Sammy!", ImgURL = "https://media.gettyimages.com/id/1471774638/photo/puppy-on-a-veterinarians-lap.jpg?s=2048x2048&w=gi&k=20&c=OWhWN9csII_1Lzg5H0CEtcIbRGFsUlhLcDK_xn14WDc=" },
                new Veterinarian { Id = 2, Name = "Mark", YearsExperience = 6, Bio = "I love dogs! I am very experienced with helping out dogs of any kind! ", ImgURL = "https://media.gettyimages.com/id/1162639281/photo/very-happy-veterinarian-getting-a-kiss-from-a-dog.jpg?s=2048x2048&w=gi&k=20&c=oTjYpYl2pTZWN2_Pdu2ChsrbarDjcryvA2RjvUB4Cok=" },
                new Veterinarian { Id = 3, Name = "Sarah", YearsExperience = 3, Bio = "Relatively new here, but I have pretty good experience working with cats and dogs. ", ImgURL = "https://media.gettyimages.com/id/170083697/photo/veterinarian-doing-a-check-up-on-a-corgi-in-clinic.jpg?s=2048x2048&w=gi&k=20&c=jjMdAsP4lGMpT8gerVV6t7CDNsgEaHKx5QRKhn_2edY=" }
                );
            //Patient data generated by ChatGPT.
            builder.Entity<Patient>().HasData(
                new Patient
                {
                    Id = 1,
                    Name = "Bella",
                    Species = "Dog",
                    Breed = "Labrador Retriever",
                    Age = 5,
                    Medications = "Heartgard",
                    MedicalHistory = "No significant history"
                },
                new Patient
                {
                    Id = 2,
                    Name = "Max",
                    Species = "Cat",
                    Breed = "Siamese",
                    Age = 7,
                    Medications = "Flea Prevention",
                    MedicalHistory = "Chronic renal disease"
                },
                new Patient
                {
                    Id = 3,
                    Name = "Charlie",
                    Species = "Dog",
                    Breed = "German Shepherd",
                    Age = 3,
                    Medications = "ProHeart",
                    MedicalHistory = "Hip dysplasia"
                },
                new Patient
                {
                    Id = 4,
                    Name = "Luna",
                    Species = "Cat",
                    Breed = "Maine Coon",
                    Age = 4,
                    Medications = "Thyroid Medication",
                    MedicalHistory = "Hyperthyroidism"
                },
                new Patient
                {
                    Id = 5,
                    Name = "Rocky",
                    Species = "Dog",
                    Breed = "Bulldog",
                    Age = 6,
                    Medications = "Allergy Medication",
                    MedicalHistory = "Chronic allergies"
                }
                );
        }
    }
}
